name: Node.js CI with Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js 24.14.1
      uses: actions/setup-node@v4
      with:
        node-version: '24.14.1'
        cache: 'yarn'

    - name: Install Dependencies
      run: yarn install --frozen-lockfile

    - name: Prepare Environment
      run: cp .env.example .env

    - name: Build and Run with Docker Compose
      run: docker compose up --build -d

    - name: Run Tests
      run: yarn test

    - name: Shutdown Containers
      if: always()
      run: docker compose down
